### PR TITLE
Article: Webmentions avec Eleventy

### PR DESCRIPTION
**Pull request by DirtyF**
Traduction 🇫🇷 de l'article de @siakaramalegos publié sur https://sia.codes/posts/webmentions-eleventy-in-depth/

### CODE REVIEW

**Comment by siakaramalegos** [comment]
I'm going to watch this PR to see when it merges and is deployed so I can link to it from the original article. Thanks for translating it!

**Comment by DirtyF** [comment]
Fixed in https://github.com/jamstatic/jamstatic-fr/commit/9b1d3b1587b85f560440e1e9ec1f784aa7889ebc

**Comment by DirtyF** [comment]
@siakaramalegos Article is now published on https://jamstatic.fr/2019/12/27/webmentions-eleventy/

**Comment by siakaramalegos** [comment]
@DirtyF great! I just added the link to your translation on my post. :)

**Comment by DirtyF** [comment]
@siakaramalegos minor french nitpick: I would list the translation as   _français_ (french, maculine)   (we say _le français_ but _la langue française_) (foreign languages are hard 😅)

**Comment by siakaramalegos** [comment]
@DirtyF thanks - another french friend told me to do it that way as an adjective for "translation". i think that makes more sense though, especially if it's read out of context. thanks!

**Pull request closed without merging**
